---
- hosts: all!localhost
  gather_subset: min
  become: true
  vars:
    tools_6_iostat: "/usr/bin/iostat -x"
    tools_7_iostat: "/bin/iostat -x"
    tools_8_iostat: "/usr/bin/iostat -x"
    tools_6_vmstat: "/usr/bin/vmstat"
    tools_7_vmstat: "/bin/vmstat"
    tools_8_vmstat: "/usr/bin/vmstat"
    tools_6_top: "/usr/bin/top -b -n 1"
    tools_7_top: "/bin/top -b -n 1"
    tools_8_top: "/usr/bin/top -b -n 1"
    tools_6_lsof: "/usr/bin/lsof"
    tools_7_lsof: "/sbin/lsof"
    tools_8_lsof: "/usr/bin/lsof"
    tools_6_df: "/bin/df -h"
    tools_7_df: "/bin/df -h"
    tools_8_df: "/usr/bin/df -h"
    tools_6_ifconfig: "/sbin/ifconfig -a"
    tools_7_ifconfig: "/sbin/ifconfig -a"
    tools_8_ifconfig: "/usr/sbin/ifconfig -a"
  tasks:
  - name: Install required packages
    yum:
      name:
        - sysstat
        - lsof
        - net-tools
    ignore_errors: true   

  - name: iostat 
    shell: "{{ lookup('vars', 'tools_'+ ansible_distribution_major_version + '_iostat')}}"
    register: iostat
    changed_when: false

  - name: vmstat
    shell: "{{ lookup('vars', 'tools_'+ ansible_distribution_major_version + '_vmstat')}}"
    register: vmstat
    changed_when: false

  - name: lsof
    shell: "{{ lookup('vars', 'tools_'+ ansible_distribution_major_version + '_lsof')}}"
    register: lsof
    changed_when: false

  - name: top -b -n 1
    shell: "{{ lookup('vars', 'tools_'+ ansible_distribution_major_version + '_top')}}"
    register: top
    changed_when: false

  - name: df -h
    shell: "{{ lookup('vars', 'tools_'+ ansible_distribution_major_version + '_df')}}"
    register: df
    changed_when: false

  - name: ifconfig -a
    shell: "{{ lookup('vars', 'tools_'+ ansible_distribution_major_version + '_ifconfig')}}"
    register: ifc
    changed_when: false

  - name: save facts gathered
    set_fact:
      output: {
        'iostat': "{{ iostat.stdout_lines }}",
        'vmstat': "{{ vmstat.stdout_lines }}",
        'lsof': "{{ lsof.stdout_lines }}",
        'top': "{{ top.stdout_lines }}",
        'df': "{{ df.stdout_lines }}",
        'ifc': "{{ ifc.stdout_lines }}",
      }

  - name: Generate Report
    copy:
      content: "{{ output | to_nice_json }}"
      dest: "/tmp/{{ inventory_hostname }}_perf.json"
    delegate_to: localhost
    ignore_errors: true

  - name: Set facts for event acknowledgement
    set_fact:
      slack_token: "{{ lookup('env','s_token') }}"
      auth_token: "{{ lookup('env','a_token') }}"
    changed_when: false
    delegate_to: localhost
    ignore_errors: true

  - name: Send Report to slack
    command: curl "https://slack.com/api/files.upload"
      -F token='{{ auth_token }}' -F initial_comment='Performance Snapshot on {{ inventory_hostname }}'
      -F channels='automation' -F title='Performance Snapshot'
      -F file=@'/tmp/{{ inventory_hostname }}_perf.json'
    register: response
    args:
      warn: false
    changed_when: false
    delegate_to: localhost
    ignore_errors: true
