---
- hosts: all
  gather_subset: min
  tasks:
  - name: Touch hc.csv
    file:
      state: touch
      path: /tmp/hc.csv
      mode: '0755'
    delegate_to: localhost
    run_once: true
    ignore_errors: true

  - name: Update Header Report.csv
    lineinfile: 
      path: /tmp/hc.csv
      line: >-
        Host Name, UPTIME, Load AVG, Avg CPU Util Free %, Avg Memory Util Used %, 
        Current SWAP Util, Current CPU Util Free %, Current Memory Util Used %, 
        Current Inodes Util, Read Only FileSystem, FileSystem Abve 70 %, VMTools Version, 
        VMTools Status, SNMPD Status, RedHat Version, Kernal Version
      insertafter: EOF
    delegate_to: localhost
    run_once: true
    ignore_errors: true

  - name: hostname 
    shell: uname -n
    register: hn
    changed_when: false
    ignore_errors: true

  - name: uptime 
    shell: xsos -o | grep 'Uptime:' | awk '{$1=""; print $0}'
    register: up
    changed_when: false
    ignore_errors: true

  - name: load average 
    shell: xsos -o | grep 'LoadAvg:' | awk '{$1=""; print $0}'
    register: lavg
    changed_when: false
    ignore_errors: true

  - name: AVG CPU Util Free % 
    shell: sar -f | grep 'Average:' | awk '{print $8}'
    register: cpua
    changed_when: false
    ignore_errors: true

  - name: AVG Memory Util Used %
    shell: sar -f | grep 'Average:' | awk '{print $4}'
    register: mema
    changed_when: false
    ignore_errors: true

  - name: Current SWAP Util 
    shell: xsos -m | grep 'Swap:' -A1 | grep -v 'Swap:' | awk '{print $3}' | rev | cut -c 2- | rev | cut -c 2-
    register: swap
    changed_when: false
    ignore_errors: true

  - name: Current CPU  Util Free 
    shell: sar 3 15 | grep --color=auto 'Average:' | awk '{print $8}'
    register: ccpu
    changed_when: false
    ignore_errors: true

  - name: Current Memory Util Used
    shell: xsos -m | grep 'excluding Buffers/Cached' | awk '{print $3}' | rev | cut -c 2- | rev | cut -c 2-
    register: cmem
    changed_when: false
    ignore_errors: true

  - name: Current Inodes Util 
    shell: df -PTi | awk '0+$6 >= 70 {print}' | awk '{print $6" ""==>"" "$7}'
    register: inodes
    changed_when: false
    ignore_errors: true

  - name: Read Only FileSystem 
    shell: cat /proc/mounts | grep 'ro,' | grep -v tmpfs
    register: rofs
    changed_when: false
    ignore_errors: true

  - name: FileSystem Above 70%
    shell: df -TPh | awk '0+$6 >= 70 {print}' | awk '{print $6" ""==>"" "$7}'
    register: fsh
    changed_when: false
    ignore_errors: true

  - name: VMTools Version
    shell: vmtoolsd -v
    register: vmtv
    changed_when: false
    ignore_errors: true

  - name: Populate service facts
    service_facts:
    ignore_errors: true

  - name: RedHat Version
    shell: cat /etc/redhat-release
    register: rhr
    changed_when: false
    ignore_errors: true

  - name: Kernal Version
    shell: uname -r
    register: kv
    changed_when: false
    ignore_errors: true

  - name: Update line Report.csv
    lineinfile: 
      path: /tmp/hc.csv
      line: >-
        "{{ hn }} , {{ up }} , {{ lavg }} , {{ cpua }} , {{ mema }} , {{ swap }} , {{ ccpu }} , {{ cmem }} , "
    #{{ inodes | default 'not found' }} , {{ rofs | default 'not found' }} , 
    #    {{ fsh | default 'not found' }} , {{ vmtv }} , {{ ansible_facts.services['vmtoolsd'].state }} , 
    #    {{ ansible_facts.services['snmpd'].state | default 'not found' }} , {{ rhr | default 'not found' }} , {{ kv }}"
      insertafter: EOF
    delegate_to: localhost
    ignore_errors: true

  - name: Set facts for event acknowledgement
    set_fact:
      slack_token: "{{ lookup('env','s_token') }}"
      auth_token: "{{ lookup('env','a_token') }}"
    no_log: true
    changed_when: false
    ignore_errors: true

  - name: Send Report to slack
    command: curl "https://slack.com/api/files.upload"
      -F token='{{ auth_token }}' -F initial_comment='Performance Snapshot on {{ inventory_hostname }}'
      -F channels='automation' -F title='Performance Snapshot'
      -F file=@'/tmp/hc.csv'
    register: response
    args:
      warn: false
    changed_when: false
    delegate_to: localhost
    run_once: true
    ignore_errors: true
