---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
  - name: get PID.
    shell: "ps aux | pgrep -i java | awk  -F '[ ]*' '{print $2}'"
    register: pid
  - debug:
     var: pid.stdout