---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
    - name: show all the hosts matching the pattern, i.e. all but the group www
      debug:
        msg: "{{ hostvars[item] }}"
      delegate_to: localhost
      run_once: true
      with_inventory_hostnames:
        - all

    - debug: 
        msg: |
          HOST Variables ("hostvars"): {{ hostvars }}  