---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
  - name: get PID.
    shell: ps aux | head -4 | awk '{print "{\"ProcessID\":\""$2"\", \"CMD\":\""$11"\", \"User\":\""$1"\"}"}'
    register: pid
  - debug:
     var: pid.stdout