---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
  - name: show all the hosts matching the pattern, i.e. all but the group www
    debug:
      msg: "{{ item }}"
    with_inventory_hostnames:
      - all