---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
  - name: get PID.
    shell: >-
      P=$(ps aux | head -4 | awk 'BEGIN {ORS=","} NR>1{print "{\"ProcessID\":\""$2"\", \"CMD\":\""$11"\", \"User\":\""$1"\"}"}'); echo "["${P::-1}"]"
    register: pid
  - set_fact:
      pids: "{{ pid.stdout }}"
  - debug:
      msg: "{{ pids }}"
  - name: show all the hosts matching the pattern, i.e. all but the group www
    debug:
      msg: "{{ item }}"
    with_inventory_hostnames:
      - all