---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
  - name: get PID.
    shell: >-
      P=$(ps aux | head -4 | awk 'BEGIN {ORS=","} NR>1{print "{ProcessID:"$2", CMD:"$11", User:"$1"}"}'); echo ${P::-1}
    register: pid
  - set_fact:
      pids: "{{ pid.stdout }}"
  - debug:
      msg: "{{ pids | to_nice_json }}"
  - debug:
      msg: "{{ pids.ProcessID }}"