---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
  - name: get PID.
    shell: TP=$(ps aux --sort -%mem | head -4 | awk 'BEGIN {ORS=","} NR>1{print "{\"ProcessID\":\""$2"\", \"CMD\":\""$11"\", \"User\":\""$1"\"}"}');${TP::-1}
    register: pid
  - debug:
     msg: "{{ pid }}"