---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
    - name: show all the hosts matching the pattern, i.e. all but the group www
      debug:
        msg: "{{ item }}"
      delegate_to: localhost
      run_once: true
      with_inventory_hostnames:
        - all

    - debug: 
        msg: |
          Module Variables ("vars"): {{ vars }} 

    - debug: 
        msg: |
          Environment Variables ("environment"): {{ env }} 

    - debug: 
        msg: |
          GROUP NAMES Variables ("group_names"): {{ group_names }}

    - debug: 
        msg: |
          GROUPS Variables ("groups"): {{ groups }}

    - debug: 
        msg: |
          HOST Variables ("hostvars"): {{ hostvars }}  