---
- name: Generate treaddump.
  hosts: all
  gather_facts: false
  tasks:
  - name: get PID.
    shell: >-
      P=$(ps aux | head -4 | awk 'BEGIN {ORS="\n"} NR>1{print "- ProcessID: "$2"\\n  CMD:\""$11"\"\\n  User:\""$1"\""}'); echo "["$P"]"
    register: pid
  - set_fact:
      pids: "{{ pid.stdout }}"
  - debug:
      msg: "{{ pids }}"
  - debug:
      msg: "{{ pids }}"