- hosts: all:!localhost
  gather_facts: false
  strategy: free

  tasks:
    - name: Starting block to make sure endpoint reboot at the end of play
      block:
        - name: Find the OS version
          setup:
            gather_subset: min

        - name: checking C drive space
          win_shell: |-
            $c=(Get-WMIObject Win32_LogicalDisk | ?{$_.DriveType -eq 3 -and $_.Name -eq 'C:'} | Select-Object @{n='FreeSpace';e={"{0:n2}" -f ($_.freespace/1gb)}}).FreeSpace | ConvertTo-JSON
            $c
          register: freespace
          changed_when: false
      
        - name: failing execution if c drive is less than 4GB
          set_fact:
            cspace: "{{ freespace.stdout | from_json }}"
          failed_when: cspace|int <= 4
          changed_when: false

        - name: Create directory structure
          win_file:
            path: C:\Temp\ansible_win_patching
            state: directory
    
        - name: Create patching log file
          win_file:
            path: C:\Temp\ansible_win_patching\ansible_patching.txt
            state: touch

        - name: Reboot before installation
          win_reboot:
            pre_reboot_delay: 120
            reboot_timeout: 600
            post_reboot_delay: 120

        - name: Start Time
          win_shell: get-date -UFormat "%Y/%m/%d %H:%M:%S" | ConvertTo-JSON
          register: sdt
          changed_when: false

        - name: Installing Windows Patches
          win_updates:
            category_names:
            - CriticalUpdates
            - DefinitionUpdates
            - SecurityUpdates
            - Updates
            - UpdateRollups
            - ServicePacks
            - FeaturePacks
            server_selection: windows_update 
            state: installed
            reboot: no
            log_path: C:\Temp\ansible_win_patching\ansible_patching.txt
          register: wsusupdates

        - name: End Time
          win_shell: $tt=(get-date) - [datetime]"{{ sdt.stdout | from_json }}"; Write-Host "{{ inventory_hostname }} :" $tt.TotalHours;
          changed_when: false

        - name: No Patches found
          include_role:
            name: returncode
          vars:
            rc_support: account
            rc_group: misconfiguration
            rc_number: 100
            rc_message: "{{ inventory_hostname }} : No Patches Found "
          when: wsusupdates.found_update_count == 0

        - name: Successfully installed patches
          include_role:
            name: returncode
          vars:
            rc_success: true
            rc_message: "{{ inventory_hostname }} : Successfully Installed Patches {{ wsusupdates }}"
          when: 
            - wsusupdates.found_update_count != 0
            - wsusupdates.found_update_count == wsusupdates.installed_update_count

      rescue:
        - name: failed
          include_role:
            name: returncode
          vars:
            rc_support: undetermined
            rc_group: unsupported_platform
            rc_number: 111
            rc_message: "{{ inventory_hostname }} : Error {{ wsusupdates }}"
