---
- hosts: all
  gather_facts: false
  tasks:
    - name: Share folders
      win_shell: GWMI -class Win32_Share

    - name: win_share
      win_share: 
        name: Utils
        path: C:\Utils
        state: present
        list: yes
        full: Administrators
