---
- hosts: all
  gather_facts: false
  vars:
    was_home: 'c:\temp'
  tasks:
    - name: Share folders
      win_path:
        elements: "{{ was_home }}"

    - debug:
        msg: "{{ was_home }}"
