---
# vars file for ansible-role-connectotion-validator
jh1_ssh_private_key: >-
  {{ lookup('env','JH1_SSH_PRIVATE_KEY') }}
jh1_ssh_private_key_passphrase: >-
  {{ lookup('env', 'JH1_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}
jh2_ssh_private_key: >-
  {{ lookup('env','JH2_SSH_PRIVATE_KEY') }}
jh2_ssh_private_key_passphrase: >-
  {{ lookup('env', 'JH2_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}
jh3_ssh_private_key: >-
  {{ lookup('env','JH3_SSH_PRIVATE_KEY') }}
jh3_ssh_private_key_passphrase: >-
  {{ lookup('env', 'JH3_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}
jh4_ssh_private_key: >-
  {{ lookup('env','JH4_SSH_PRIVATE_KEY') }}
jh4_ssh_private_key_passphrase: >-
  {{ lookup('env', 'JH4_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}
jh5_ssh_private_key: >-
  {{ lookup('env','JH5_SSH_PRIVATE_KEY') }}
jh5_ssh_private_key_passphrase: >-
  {{ lookup('env', 'JH5_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}
no_of_hop: >-
  {{ hostvars[hostvars['localhost']['affected_host']]
  ['jumphost_credential']|default(0) }}
